
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ResponsiveEcomerce from "../components/ResponsiveEcomerce";
import './category.css';
import { CheckoutProvider } from "@/providers/CheckoutProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function deshboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CheckoutProvider>
                <ResponsiveEcomerce></ResponsiveEcomerce>

            <div className="flex  w-screen">
                 {children}

            
            </div>
       </CheckoutProvider>


      
       
      </body>
    </html>
  );
}
