import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextAuthjsProvider from "@/providers/NextAuthjsProvider";

import './deshboard.css';

import NextDeshboardProvider from "@/providers/NextDeshboardProvider";
import  Deshboard from '@/components/DeshboardNavber/Deshboard';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function deshboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthjsProvider>

          <NextDeshboardProvider>
            <div className="flex  w-screen">
<Deshboard></Deshboard>
             {children}
            </div>
            
            </NextDeshboardProvider>

        </NextAuthjsProvider>
      
       
      </body>
    </html>
  );
}
